# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ['.', '--check', '--diff', '--config', './pyproject.toml']
        language_version: python3
        exclude: 'migrations|manage\.py|wsgi\.py'
        additional_dependencies: ["click==8.0.4"]
