# Generated by Django 3.0 on 2020-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0077_auto_20200820_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='A keyword (beyond EDAM ontology scope).', max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EventKeyword',
        ),
        migrations.AlterField(
            model_name='bioinformaticsteam',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the bioinformatics team.', related_name='bioinformaticsTeams', to='ifbcatsandbox_api.Keyword'),
        ),
        migrations.AlterField(
            model_name='event',
            name='keywords',
            field=models.ManyToManyField(help_text='A keyword (beyond EDAM ontology scope) describing the event.', related_name='events', to='ifbcatsandbox_api.Keyword'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the training material.', related_name='trainingMaterials', to='ifbcatsandbox_api.Keyword'),
        ),
    ]
