# Generated by Django 3.0 on 2020-08-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0091_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTopic',
        ),
        migrations.AlterField(
            model_name='bioinformaticsteam',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the bioinformatics team.', related_name='bioinformaticsTeams', to='ifbcatsandbox_api.Topic'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the scope of the event.', related_name='events', to='ifbcatsandbox_api.Topic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the expertise of the project.', related_name='projects', to='ifbcatsandbox_api.Topic'),
        ),
        migrations.AlterField(
            model_name='team',
            name='expertise',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the expertise of the team.', related_name='teams', to='ifbcatsandbox_api.Topic'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the scope of the training material.', related_name='trainingMaterials', to='ifbcatsandbox_api.Topic'),
        ),
    ]
