version: '3'

services:
  web:
    volumes:
      - .:/code # for dev purpose only !!!
      - ./import_data:/code/import_data # for dev purpose only !!!


  # The Database manager (adminer)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"