version: '3'

services:

  db:
    image: postgres:12
    volumes:
      - /var/ifbcat/db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./resources/default.ini
      - ./local.ini

  web:
    build:
      context: ./
      dockerfile: django.dockerfile
    restart:
      always
    entrypoint: /docker-entrypoint.sh
    command: gunicorn --reload ifbcat.wsgi -b 0.0.0.0:8000
    environment:
      - CI_COMMIT_SHA=$CI_COMMIT_SHA
      - CI_COMMIT_DATE=$CI_COMMIT_DATE
    env_file:
      - ./resources/default.ini
      - ./local.ini
    volumes:
      - /var/ifbcat/static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  # The Database manager (adminer)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/ifbcat/static:/static:ro
    ports:
      - "8080:8080"
    depends_on:
      - web

  nginx-https:
    image: nginx:1.19-alpine
    volumes:
      - ./resources/nginx-https.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/ifbcat/static:/static:ro
      - /etc/ssl/certs/wildcard-chained-france-bioinformatique.crt:/wildcard-chained-france-bioinformatique.crt:ro
      - /etc/ssl/private/wildcard-france-bioinformatique.key:/wildcard-france-bioinformatique.key:ro
    ports:
      - "443:8443"
    depends_on:
      - web
