services:

  db:
    image: postgres:18
    volumes:
      - /var/ifbcat/db_data:/var/lib/postgresql
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./resources/default.ini
      - ./local.ini

  web:
    build:
      context: ./
      dockerfile: django.dockerfile
    restart:
      always
    entrypoint: /docker-entrypoint.sh
    environment:
      - CI_COMMIT_SHA=${CI_COMMIT_SHA:-xx}
      - CI_COMMIT_DATE=${CI_COMMIT_DATE:-xx}
    env_file:
      - ./resources/default.ini
      - ./local.ini
    volumes:
      - /var/ifbcat/static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./resources/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - /var/ifbcat/static:/static:ro
    ports:
      - "8080:8080"
    environment:
     - NGINX_FROWARD_PROTO=https
    depends_on:
      - web
