version: '3'

services:

  db:
    image: postgres:12
#    build:
#      context: ./
#      dockerfile: postgres.dockerfile
    volumes:
      - /var/ifbcat/db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./resources/default.ini
      - ./local.ini
    #environment:
    #  POSTGRES_USER: "ifb_user"
    #  POSTGRES_PASSWORD: "pass"
    #  POSTGRES_DB: "ifb_catalog"
#      PGDATA: /var/lib/postgresql/data/pgdata

  web:
    build:
      context: ./
      dockerfile: django.dockerfile
    restart:
      always
    entrypoint: /docker-entrypoint.sh
    # command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: gunicorn --reload ifbcatsandbox.wsgi -b 0.0.0.0:8000
    env_file:
      - ./resources/default.ini
      - ./local.ini
    volumes:
      - .:/code # for dev purpose !!!
      - /var/ifbcat/static:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    # user: "${UID}:${GID}"
  # The Database manager (adminer)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  nginx:
    image: nginx:1.19-alpine
    #build:
    #  context: ./
    #  dockerfile: nginx.dockerfile
    volumes:
    #  - .:/code
      - ./resources/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/ifbcat/static:/static
      - /etc/ssl/certs/wildcard-chained-france-bioinformatique.crt:/etc/ssl/certs/wildcard-chained-france-bioinformatique.crt
      - /etc/ssl/private/wildcard-france-bioinformatique.key:/etc/ssl/private/wildcard-france-bioinformatique.key
    ports:
      - "8080:8080"
      - "443:8443"
    depends_on:
      - web


#volumes:
#  db_data:
