# Generated by Django 2.2 on 2020-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0002_auto_20200627_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orcidid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
