# Generated by Django 3.0 on 2020-07-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0018_eventkeyword_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkeyword',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='ifbcat_api.Event'),
        ),
    ]
