# Generated by Django 3.0 on 2020-07-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0021_auto_20200715_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventkeyword',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventprerequisite',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='keywords',
            field=models.ManyToManyField(help_text='A keyword (beyond EDAM ontology scope) describing the event.', related_name='events', to='ifbcat_api.EventKeyword'),
        ),
        migrations.AddField(
            model_name='event',
            name='prerequisites',
            field=models.ManyToManyField(help_text="A skill which the audience should (ideally) possess to get the most out of the event, e.g. 'Python'.", related_name='events', to='ifbcat_api.EventPrerequisite'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(help_text='URI of EDAM Topic term describing the scope of the event.', related_name='events', to='ifbcat_api.EventTopic'),
        ),
    ]
