# Generated by Django 3.0 on 2020-07-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0022_auto_20200715_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventkeyword',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='eventprerequisite',
            name='user_profile',
        ),
    ]
