# Generated by Django 3.0 on 2020-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0024_auto_20200716_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accessibility',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], help_text='Whether the event is public or private.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(blank=True, choices=[('Free', 'Free'), ('Free to academics', 'Free To Academics'), ('Concessions available', 'Concessions Available')], help_text="Monetary cost to attend the event, e.g. 'Free to academics'.", max_length=255),
        ),
    ]
