# Generated by Django 3.0 on 2020-07-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0025_auto_20200716_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='news_text',
            new_name='news',
        ),
    ]
