# Generated by Django 3.0 on 2020-07-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0027_auto_20200716_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maxParticipants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of participants to the event.', null=True),
        ),
    ]
