# Generated by Django 3.0 on 2020-07-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0029_auto_20200716_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cost',
            new_name='costs',
        ),
    ]
