# Generated by Django 3.0 on 2020-07-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0030_auto_20200716_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcost',
            name='cost',
            field=models.CharField(help_text="Monetary cost to attend the event, e.g. 'Free to academics'.", max_length=255, unique=True),
        ),
    ]
