# Generated by Django 3.0.7 on 2020-07-20 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0032_auto_20200716_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField(help_text='The start date of the event.')),
                ('dateEnd', models.DateField(blank=True, help_text='The end date of the event.', null=True)),
                ('timeStart', models.TimeField(blank=True, help_text='The start time of the event.', null=True)),
                ('timeEnd', models.TimeField(blank=True, help_text='The end time of the event.', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='maxParticipants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of participants to the event.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Workshop', 'Workshop'), ('Training course', 'Training course'), ('Meeting', 'Meeting'), ('Conference', 'Conference')], help_text="The type of event e.g. 'Training course'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='eventcost',
            name='cost',
            field=models.CharField(choices=[('Free', 'Free'), ('Free to academics', 'Free to academics'), ('Priced', 'Priced'), ('Concessions available', 'Concessions available')], help_text="Monetary cost to attend the event, e.g. 'Free to academics'.", max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dates',
            field=models.ManyToManyField(help_text='Dates on which the event takes place', related_name='dates', to='ifbcat_api.EventDate'),
        ),
    ]
