# Generated by Django 3.0 on 2020-07-20 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0035_auto_20200720_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elixirplatform',
            name='deputies',
            field=models.ManyToManyField(blank=True, help_text='Deputy coordinator of the ELIXIR Platform activities in France.', related_name='elixirPlatformDeputies', to=settings.AUTH_USER_MODEL),
        ),
    ]
