# Generated by Django 3.0 on 2020-07-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0038_event_elixirplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dates',
            field=models.ManyToManyField(blank=True, help_text='Date(s) and optional time periods on which the event takes place.', related_name='dates', to='ifbcat_api.EventDate'),
        ),
    ]
