# Generated by Django 3.0 on 2020-07-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0041_auto_20200720_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dates',
            field=models.ManyToManyField(help_text='Date(s) and optional time periods on which the event takes place.', related_name='events', to='ifbcat_api.EventDate'),
        ),
    ]
