# Generated by Django 3.0 on 2020-07-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0043_auto_20200720_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='elixirPlatform',
            new_name='elixirPlatforms',
        ),
        migrations.AddField(
            model_name='event',
            name='communities',
            field=models.ManyToManyField(help_text='Community for which the event is relevant.', related_name='events', to='ifbcat_api.Community'),
        ),
        migrations.AddField(
            model_name='event',
            name='hostedBy',
            field=models.ManyToManyField(help_text='Organisation which is hosting the event.', related_name='events', to='ifbcat_api.Organisation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dates',
            field=models.ManyToManyField(help_text='Date(s) and optional time periods on which the event takes place.', related_name='events', to='ifbcat_api.EventDate'),
        ),
    ]
