# Generated by Django 3.0 on 2020-07-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0045_auto_20200720_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(help_text='Name of the organisation.', max_length=255),
        ),
    ]
