# Generated by Django 3.0 on 2020-07-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0046_auto_20200720_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='field',
            field=models.CharField(blank=True, choices=[('Computer science', 'Computer science'), ('Biotechnology', 'Biotechnology'), ('Environmental science', 'Environmental science'), ('Agricultural science', 'Agricultural science'), ('Biomedical science', 'Biomedical science'), ('Biology', 'Biology')], help_text='Controlled vocabulary of application areas of organisations and bioinformatics teams.', max_length=255, unique=True),
        ),
    ]
