# Generated by Django 3.0 on 2020-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0050_organisation_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='communities',
            field=models.ManyToManyField(blank=True, help_text='Community for which the event is relevant.', related_name='events', to='ifbcat_api.Community'),
        ),
        migrations.AlterField(
            model_name='event',
            name='elixirPlatforms',
            field=models.ManyToManyField(blank=True, help_text='ELIXIR Platform to which the event is relevant.', related_name='events', to='ifbcat_api.ElixirPlatform'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hostedBy',
            field=models.ManyToManyField(blank=True, help_text='Organisation which is hosting the event.', related_name='events', to='ifbcat_api.Organisation'),
        ),
    ]
