# Generated by Django 3.0 on 2020-07-21 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0053_auto_20200721_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contactId',
            field=models.ForeignKey(help_text='IFB ID of person to contact about the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventContactId', to=settings.AUTH_USER_MODEL),
        ),
    ]
