# Generated by Django 3.0 on 2020-07-20 19:17

from django.db import migrations, models

from django.utils.translation import gettext_lazy as _


def migration_code(apps, schema_editor):
    EventCost = apps.get_model("ifbcat_api", "EventCost")

    # translated is here just to be extracted by make_messages if needed
    for key, translated in [
        ('Free', _('Free')),
        ('Free to academics', _('Free to academics')),
        ('Priced', _('Priced')),
        ('Concessions available', _('Concessions available')),
    ]:
        EventCost.objects.get_or_create(cost=key,)


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcat_api', '0056_project_user_profile'),
    ]

    operations = [
        migrations.RunPython(migration_code, reverse_code=migrations.RunPython.noop),
    ]
