# Generated by Django 3.0 on 2020-07-20 19:17

from django.db import migrations, models

from django.utils.translation import gettext_lazy as _


def migration_code(apps, schema_editor):
    OrganisationField = apps.get_model("ifbcat_api", "OrganisationField")

    for key, translated in [
        ('Computer science', _('Computer science')),
        ('Biotechnology', _('Biotechnology')),
        ('Environmental science', _('Environmental science')),
        ('Agricultural science', _('Agricultural science')),
        ('Biomedical science', _('Biomedical science')),
        ('Biology', _('Biology')),
    ]:
        OrganisationField.objects.get_or_create(field=key,)


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcat_api', '0057_create_cost'),
    ]

    operations = [
        migrations.RunPython(migration_code, reverse_code=migrations.RunPython.noop),
    ]
