# Generated by Django 3.0.7 on 2020-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0060_auto_20200722_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMaterialLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The professional roles of the expected audience of the training event or material.', max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audiencerole',
            name='audienceRole',
            field=models.CharField(help_text='The professional roles of the expected audience of the training event or material.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='audiencetype',
            name='audienceType',
            field=models.CharField(help_text='The education or professional level of the expected audience of the training event or material.', max_length=255, unique=True),
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='license',
        ),
        migrations.AddField(
            model_name='trainingmaterial',
            name='license',
            field=models.ManyToManyField(blank=True, help_text='License under which the training material is made available.', to='ifbcat_api.TrainingMaterialLicense'),
        ),
    ]
