# Generated by Django 3.0 on 2020-08-12 16:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0064_auto_20200812_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEventMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField(help_text='The start date of the training event.')),
                ('dateEnd', models.DateField(help_text='The end date of the training event.')),
                ('numParticipants', models.PositiveSmallIntegerField(blank=True, help_text='Number of participants at the training event.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainerName', models.CharField(blank=True, help_text='Name of person who is providing training at the training event.', max_length=255)),
                ('trainerEmail', models.EmailField(help_text='Email of person who is providing training at the training event.', max_length=254)),
                ('trainerId', models.ForeignKey(help_text='IFB ID of person who is providing training at the training event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainerId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of institutional entity that is sponsoring the event.', max_length=255)),
                ('homepage', models.URLField(help_text='Homepage URL of the sponsor of the event.', max_length=255)),
                ('organisationId', models.ForeignKey(help_text='IFB ID of a event-sponsoring organisation registered in the IFB catalogue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventSponsor', to='ifbcat_api.Organisation')),
            ],
        ),
    ]
