# Generated by Django 3.0 on 2020-08-13 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0065_eventsponsor_trainer_trainingeventmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainerId',
            field=models.ForeignKey(help_text='IFB ID of person who is providing training at the training event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventTrainerId', to=settings.AUTH_USER_MODEL),
        ),
    ]
