# Generated by Django 3.0 on 2020-08-18 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0069_auto_20200813_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the team.', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Description of the team.')),
                ('homepage', models.URLField(blank=True, help_text='Homepage of the team.', max_length=255, null=True)),
                ('deputies', models.ManyToManyField(blank=True, help_text='Deputy leader(s) of the team.', related_name='teamDeputies', to=settings.AUTH_USER_MODEL)),
                ('expertise', models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the expertise of the project.', related_name='teams', to='ifbcat_api.EventTopic')),
                ('leader', models.ForeignKey(help_text='Leader of the team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamLeader', to=settings.AUTH_USER_MODEL)),
                ('maintainers', models.ManyToManyField(help_text='Maintainer(s) of the team metadata in IFB catalogue.', related_name='teamMaintainers', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(help_text='Members of the team.', related_name='teamMembers', to=settings.AUTH_USER_MODEL)),
                ('scientificLeader', models.ForeignKey(help_text='Scientific leader of the team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamScientificLeader', to=settings.AUTH_USER_MODEL)),
                ('technicalLeader', models.ForeignKey(help_text='Technical leader of the team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamTechnicalLeader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the scope of the event.', related_name='events', to='ifbcat_api.EventTopic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the expertise of the project.', related_name='projects', to='ifbcat_api.EventTopic'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the scope of the training material.', related_name='trainingMaterials', to='ifbcat_api.EventTopic'),
        ),
        migrations.CreateModel(
            name='BioiformaticsTeam',
            fields=[
                ('team_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ifbcat_api.Team')),
                ('orgid', models.CharField(help_text='Organisation ID (GRID or ROR ID) of the team.', max_length=255, unique=True)),
                ('unitId', models.CharField(blank=True, help_text='Unit ID (unique identifier of research or service unit) that the Bioinformatics Team belongs to.', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Postal address of the bioinformatics team.')),
                ('ifbMembership', models.CharField(choices=[('IFB platform', 'IFB platform'), ('IFB-associated team', 'IFB-associated team'), ('Not a member', 'Not a member')], help_text='Type of membership the bioinformatics team has to IFB.', max_length=255)),
                ('publications', models.CharField(blank=True, help_text='Unique identier (DOI) of the training material, e.g. a Zenodo DOI.', max_length=255, null=True, unique=True)),
                ('certification', models.CharField(blank=True, choices=[('Certificate 1', 'Certificate 1')], help_text='Certification (e.g. ISO) of the bioinformatics team.', max_length=255)),
                ('affiliatedWith', models.ManyToManyField(blank=True, help_text='Organisation(s) to which the bioinformatics team is affiliated.', related_name='bioinformaticsTeamsAffiliatedWith', to='ifbcat_api.Organisation')),
                ('communities', models.ManyToManyField(blank=True, help_text='Communities in which the bioinformatics team is involved.', related_name='bioinformaticsTeams', to='ifbcat_api.Community')),
                ('fields', models.ManyToManyField(blank=True, help_text='A broad field that the bioinformatics team serves.', related_name='bioinformaticsTeams', to='ifbcat_api.OrganisationField')),
                ('fundedBy', models.ManyToManyField(help_text='Organisation(s) that funds the bioinformatics team.', related_name='bioinformaticsTeamsFundedBy', to='ifbcat_api.Organisation')),
                ('keywords', models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the bioinformatics team.', related_name='bioinformaticsTeams', to='ifbcat_api.EventKeyword')),
                ('platforms', models.ManyToManyField(blank=True, help_text='ELIXIR Platform(s) in which the bioinformatics team is involved.', related_name='bioinformaticsTeams', to='ifbcat_api.ElixirPlatform')),
                ('projects', models.ManyToManyField(blank=True, help_text='Project(s) that the bioinformatics team is involved with, supports or hosts.', related_name='bioinformaticsTeams', to='ifbcat_api.Project')),
                ('topics', models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the bioinformatics team.', related_name='bioinformaticsTeams', to='ifbcat_api.EventTopic')),
            ],
            bases=('ifbcat_api.team',),
        ),
    ]
