# Generated by Django 3.0 on 2020-08-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0072_auto_20200819_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(help_text='The team which is delivering the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='ifbcat_api.Team'),
        ),
    ]
