# Generated by Django 3.0 on 2020-08-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0073_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='computingfacility',
            name='team',
            field=models.ForeignKey(help_text='The team which is maintaining the computing facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computingFacility', to='ifbcat_api.Team'),
        ),
    ]
