# Generated by Django 3.0 on 2020-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0075_auto_20200819_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sponsoredBy',
            field=models.ManyToManyField(blank=True, help_text='An institutional entity that is sponsoring the event.', related_name='events', to='ifbcat_api.EventSponsor'),
        ),
    ]
