# Generated by Django 3.0 on 2020-08-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0077_auto_20200820_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='A keyword (beyond EDAM ontology scope).', max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventkeyword',
            name='keyword',
            field=models.CharField(help_text='A keyword (beyond EDAM ontology scope).', max_length=255, unique=True),
        ),
    ]
