# Generated by Django 3.0 on 2020-08-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0078_auto_20200820_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computingfacility',
            options={'verbose_name_plural': 'Computing facilities'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
