# Generated by Django 3.0 on 2020-08-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0079_auto_20200820_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticsteam',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the bioinformatics team.', related_name='bioinformaticsTeams', to='ifbcat_api.Keyword'),
        ),
    ]
