# Generated by Django 3.0 on 2020-08-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0080_auto_20200820_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='keywords',
            field=models.ManyToManyField(help_text='A keyword (beyond EDAM ontology scope) describing the event.', related_name='events', to='ifbcat_api.Keyword'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the training material.', related_name='trainingMaterials', to='ifbcat_api.Keyword'),
        ),
    ]
