# Generated by Django 3.0 on 2020-08-26 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0086_servicesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubmission',
            name='authors',
            field=models.ManyToManyField(help_text='The person(s) who submitted the service proposal to the ELIXIR FR SDP process.', related_name='ServiceSubmissionAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicesubmission',
            name='submitters',
            field=models.ManyToManyField(help_text='The person(s) who submitted the service proposal to the ELIXIR FR SDP process.', related_name='ServiceSubmissionSubmitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
