# Generated by Django 3.0 on 2020-08-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0090_delete_organisationfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='URI of EDAM Topic term describing scope or expertise.', max_length=255, unique=True)),
            ],
        ),
    ]
