# Generated by Django 3.0 on 2020-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0091_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticsteam',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the bioinformatics team.', related_name='bioinformaticsTeams', to='ifbcat_api.Topic'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the scope of the event.', related_name='events', to='ifbcat_api.Topic'),
        ),
        migrations.AlterField(
            model_name='eventtopic',
            name='topic',
            field=models.CharField(help_text='URI of EDAM Topic term describing scope or expertise.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the expertise of the project.', related_name='projects', to='ifbcat_api.Topic'),
        ),
        migrations.AlterField(
            model_name='team',
            name='expertise',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the expertise of the team.', related_name='teams', to='ifbcat_api.Topic'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the scope of the training material.', related_name='trainingMaterials', to='ifbcat_api.Topic'),
        ),
    ]
