# Generated by Django 3.0 on 2020-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0098_auto_20200902_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='homepage',
            field=models.URLField(help_text='URL of event homepage.', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='homepage',
            field=models.URLField(help_text='Homepage of the team.', max_length=255),
        ),
    ]
