# Generated by Django 3.0 on 2020-09-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0100_auto_20200902_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingeventmetrics',
            name='trainingEvent',
            field=models.ForeignKey(help_text='Training event to which the metrics are associated.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ifbcat_api.TrainingEvent'),
        ),
    ]
