# Generated by Django 3.0.7 on 2020-09-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0104_auto_20200903_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='communities',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='elixirPlatforms',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='audienceRoles',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='audienceTypes',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='providedBy',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='resource_ptr',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='project',
            name='uses',
        ),
        migrations.RemoveField(
            model_name='service',
            name='trainingMaterials',
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='computingFacilities',
        ),
        migrations.RemoveField(
            model_name='trainingevent',
            name='trainingMaterials',
        ),
        migrations.DeleteModel(
            name='ComputingFacility',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='TrainingMaterial',
        ),
    ]
