# Generated by Django 3.0.7 on 2020-09-04 07:17

from django.db import migrations, models
import django.db.models.deletion
import ifbcat_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0107_auto_20200903_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doi',
            name='doi',
            field=models.CharField(help_text='A digital object identifier (DOI) of a publication or training material.', max_length=255, unique=True, validators=[ifbcat_api.validators.validate_doi]),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='doi',
            field=models.ForeignKey(blank=True, help_text='Unique identier (DOI) of the training material, e.g. a Zenodo DOI.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbcat_api.Doi'),
        ),
    ]
