# Generated by Django 3.0.7 on 2020-09-04 15:35

import django.core.validators
from django.db import migrations, models
import ifbcat_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0108_auto_20200904_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioinformaticsteam',
            name='orgid',
            field=models.CharField(blank=True, help_text='Organisation ID (GRID or ROR ID) of the team.', max_length=255, null=True, unique=True, validators=[ifbcat_api.validators.validate_grid_or_ror_id]),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='name',
            field=models.CharField(help_text='Name of the resource.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Should only contains char such as ^[a-zA-Z0-9 \\-_~]', regex='^[a-zA-Z0-9 \\-_~]+$')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Full name / title of the event.', max_length=255, validators=[django.core.validators.RegexValidator(message='Should only contains char such as ^[a-zA-Z0-9 \\-_~]', regex='^[a-zA-Z0-9 \\-_~]+$')]),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(help_text='A keyword (beyond EDAM ontology scope).', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Should only contains char such as ^[a-zA-Z0-9 \\-_~]', regex='^[a-zA-Z0-9 \\-_~]+$')]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(help_text='Name of the organisation.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Should only contains char such as ^[a-zA-Z0-9 \\-_~]', regex='^[a-zA-Z0-9 \\-_~]+$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Should only contains char such as ^[a-zA-Z0-9 \\-_~]', regex='^[a-zA-Z0-9 \\-_~]+$')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Name of the service.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Should only contains char such as ^[a-zA-Z0-9 \\-_~]', regex='^[a-zA-Z0-9 \\-_~]+$')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Name of the team.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Should only contains char such as ^[a-zA-Z0-9 \\-_~]', regex='^[a-zA-Z0-9 \\-_~]+$')]),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='name',
            field=models.CharField(help_text='Name of the resource.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Should only contains char such as ^[a-zA-Z0-9 \\-_~]', regex='^[a-zA-Z0-9 \\-_~]+$')]),
        ),
    ]
