# Generated by Django 3.0.7 on 2020-09-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0111_auto_20200904_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioinformaticsteam',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL of logo.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='eventsponsor',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL of logo.', max_length=512, null=True),
        ),
    ]
