# Generated by Django 3.0.7 on 2020-09-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0112_auto_20200907_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Full name / title of the event.', max_length=255),
        ),
    ]
