# Generated by Django 3.0.7 on 2020-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0113_auto_20200911_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL of logo of event.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL of logo of organisation.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='bioinformaticsteam',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL of logo of the bioinformatics team.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='eventsponsor',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL of logo of event sponsor.', max_length=512, null=True),
        ),
    ]
