# Generated by Django 3.0.7 on 2020-09-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0115_auto_20200914_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expertise',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the expertise of a person (IFB catalogue user).', related_name='userprofiles', to='ifbcat_api.Topic'),
        ),
    ]
