# Generated by Django 3.0.7 on 2020-09-29 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0118_auto_20200929_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='deputies',
            field=models.ManyToManyField(help_text='Deputy leader(s) of the team.', related_name='teamDeputies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='scientificLeader',
        ),
        migrations.AddField(
            model_name='team',
            name='scientificLeaders',
            field=models.ManyToManyField(help_text='Scientific leader(s) of the team.',
                                         related_name='teamScientificLeaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='technicalLeader',
        ),
        migrations.AddField(
            model_name='team',
            name='technicalLeaders',
            field=models.ManyToManyField(help_text='Technical leader(s) of the team.',
                                         related_name='teamTechnicalLeaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
