# Generated by Django 3.0.7 on 2020-10-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0119_auto_20200929_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotoolsID', models.CharField(max_length=100)),
                ('biotoolsCURIE', models.CharField(max_length=109)),
                ('citations', models.CharField(blank=True, max_length=1000, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('access_condition', models.TextField(blank=True, null=True)),
                ('contact_support', models.CharField(blank=True, max_length=1000, null=True)),
                ('tool_license', models.CharField(blank=True, max_length=1000, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('annual_visits', models.IntegerField(blank=True, null=True)),
                ('unique_visits', models.IntegerField(blank=True, null=True)),
                ('maturity', models.CharField(blank=True, max_length=1000, null=True)),
                ('homepage', models.CharField(blank=True, max_length=1000, null=True)),
                ('cost', models.CharField(blank=True, max_length=1000, null=True)),
                ('input_data', models.CharField(blank=True, max_length=1000, null=True)),
                ('output_data', models.CharField(blank=True, max_length=1000, null=True)),
                ('primary', models.CharField(blank=True, max_length=1000, null=True)),
                ('additionDate', models.DateTimeField(blank=True, null=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
