# Generated by Django 3.0.7 on 2020-10-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0121_auto_20201016_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
