# Generated by Django 3.0.7 on 2020-10-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0122_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
