# Generated by Django 3.0.7 on 2020-10-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0124_auto_20201020_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('additionDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='scientific_topics',
            field=models.ManyToManyField(blank=True, to='ifbcat_api.Topic'),
        ),
        migrations.AddField(
            model_name='tool',
            name='operatingSystem',
            field=models.ManyToManyField(blank=True, to='ifbcat_api.OperatingSystem'),
        ),
    ]
