# Generated by Django 3.0.7 on 2020-10-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0129_tool_primary_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='primary_publications',
            new_name='primary_publication',
        ),
    ]
