# Generated by Django 3.0.7 on 2020-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0130_auto_20201021_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tooltype',
            name='name',
            field=models.CharField(blank=True, choices=[('Bioinformatics portal', 'Bioinformatics portal'), ('Command-line tool', 'Command-line tool'), ('Database portal', 'Database portal'), ('Desktop application', 'Desktop application'), ('Library', 'Library'), ('Ontology', 'Ontology'), ('Plug-in', 'Plug-in'), ('Script', 'Script'), ('SPARQL endpoint', 'SPARQL endpoint'), ('Suite', 'Suite'), ('Web application', 'Web application'), ('Web API', 'Web API'), ('Web service', 'Web service'), ('Workbench', 'Workbench'), ('Workflow', 'Workflow')], max_length=100, null=True, unique=True),
        ),
    ]
