# Generated by Django 3.0.7 on 2020-10-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0131_auto_20201022_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(blank=True, choices=[('LINUX', 'Linux'), ('WINDOWS', 'Windows'), ('MAC', 'Mac')], max_length=100, null=True, unique=True),
        ),
    ]
