# Generated by Django 3.0.7 on 2020-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0134_auto_20201109_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='additionDate',
            new_name='addition_date',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='lastUpdate',
            new_name='last_update',
        ),
        migrations.AddField(
            model_name='tool',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the tool.', related_name='toolsKeywords', to='ifbcat_api.Keyword'),
        ),
        migrations.AlterField(
            model_name='team',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the team.', related_name='teamsKeywords', to='ifbcat_api.Keyword'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='homepage',
            field=models.URLField(blank=True, help_text='Homepage of the tool.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
