# Generated by Django 3.0.7 on 2020-11-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0136_create_user_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
