# Generated by Django 3.0.7 on 2020-11-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0137_delete_newsitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='tool',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
