# Generated by Django 3.0.11 on 2020-11-26 16:17

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0139_auto_20201124_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='uri',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, help_text='Definition of the EDAM term', max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='synonyms',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Narrow synonyms', null=True, size=8),
        ),
    ]
