# Generated by Django 3.0.11 on 2020-12-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0140_auto_20201126_1617'),
        ('ifbcat_api', '0138_auto_20201122_1815'),
    ]

    operations = [
    ]
