# Generated by Django 3.0.11 on 2021-01-13 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0140_auto_20201126_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='team',
            name='deputies',
            field=models.ManyToManyField(help_text='Deputy leader(s) of the team.', null=True, related_name='teamsDeputies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='maintainers',
            field=models.ManyToManyField(help_text='Maintainer(s) of the team metadata in IFB catalogue.', null=True, related_name='teamsMaintainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='scientificLeaders',
            field=models.ManyToManyField(help_text='Scientific leader(s) of the team.', null=True, related_name='teamsScientificLeaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='technicalLeaders',
            field=models.ManyToManyField(help_text='Technical leader(s) of the team.', null=True, related_name='teamsTechnicalLeaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='dateCreation',
            field=models.DateField(blank=True, help_text='Date when the training material was created.', null=True),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='dateUpdate',
            field=models.DateField(blank=True, help_text='Date when the training material was updated.', null=True),
        ),
    ]
