# Generated by Django 3.0.11 on 2021-01-14 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0141_auto_20210113_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='deputies',
            field=models.ManyToManyField(blank=True, help_text='Deputy leader(s) of the team.', related_name='teamsDeputies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='maintainers',
            field=models.ManyToManyField(blank=True, help_text='Maintainer(s) of the team metadata in IFB catalogue.', related_name='teamsMaintainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='scientificLeaders',
            field=models.ManyToManyField(blank=True, help_text='Scientific leader(s) of the team.', related_name='teamsScientificLeaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='technicalLeaders',
            field=models.ManyToManyField(blank=True, help_text='Technical leader(s) of the team.', related_name='teamsTechnicalLeaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
