# Generated by Django 3.0.11 on 2021-02-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0143_auto_20210114_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organisedByBioinformaticsTeams',
        ),
        migrations.RemoveField(
            model_name='service',
            name='bioinformaticsTeams',
        ),
        migrations.AddField(
            model_name='service',
            name='teams',
            field=models.ManyToManyField(help_text='The bioinformatics team(s) that provides this service.', related_name='services', to='ifbcat_api.Team'),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='providedBy',
            field=models.ForeignKey(help_text='The bioinformatics team that provides the computing facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computingFacilityProvidedBy', to='ifbcat_api.Team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisedByTeams',
            field=models.ManyToManyField(blank=True, help_text='A Team that is organizing the event.', related_name='organized_events_as_bioinfo', to='ifbcat_api.Team'),
        ),
        migrations.AlterField(
            model_name='service',
            name='computingFacilities',
            field=models.ManyToManyField(blank=True, help_text='Computing facilities provided by the service.', related_name='servicesComputingFacilities', to='ifbcat_api.Team'),
        ),
        migrations.AlterField(
            model_name='trainingmaterial',
            name='providedBy',
            field=models.ManyToManyField(blank=True, help_text='The team that provides the training material.', related_name='trainingMaterials', to='ifbcat_api.Team'),
        ),
        migrations.DeleteModel(
            name='BioinformaticsTeam',
        ),
    ]
