# Generated by Django 3.0.11 on 2021-01-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0143_auto_20210114_1543'),
        ('ifbcat_api', '0141_merge_20201201_1548'),
    ]

    operations = [
    ]
