# Generated by Django 3.0.11 on 2021-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0144_auto_20210215_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ifbMembership',
            field=models.CharField(choices=[('IFB platform', 'IFB platform'), ('IFB-associated team', 'IFB-associated team'), ('Not a member', 'Not a member')], default='Not a member', help_text='Type of membership the bioinformatics team has to IFB.', max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='platforms',
            field=models.ManyToManyField(blank=True, help_text='ELIXIR Platform(s) in which the bioinformatics team is involved.', related_name='teamsPlatforms', to='ifbcat_api.ElixirPlatform'),
        ),
    ]
