# Generated by Django 3.0.11 on 2021-03-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0146_auto_20210215_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computingfacility',
            name='team',
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='providedBy',
            field=models.ForeignKey(help_text='The team which is maintaining the computing facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbcat_api.Team'),
        ),
    ]
