# Generated by Django 3.0.11 on 2021-03-03 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0147_auto_20210303_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computingfacility',
            name='serverDescription',
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='cpuCores',
            field=models.PositiveIntegerField(blank=True, help_text='Number of CPU cores provided by the computing facility.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='cpuHoursYearly',
            field=models.PositiveIntegerField(blank=True, help_text='Number of CPU hours provided by the computing facility in the last year.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='ramGb',
            field=models.PositiveIntegerField(blank=True, help_text='RAM (GB) provided by the computing facility.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='ramPerCoreGb',
            field=models.PositiveIntegerField(blank=True, help_text='RAM (GB) per CPU core provided by the Platform physical infrastructure.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='storageTb',
            field=models.PositiveIntegerField(blank=True, help_text='Amount of storage (TB) provided by the computing facility.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='usersYearly',
            field=models.PositiveIntegerField(blank=True, help_text='Number of users served by the computing facility in the last year.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
