# Generated by Django 3.0.11 on 2021-03-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0150_auto_20210303_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='trainingEvents',
        ),
        migrations.RemoveField(
            model_name='trainingeventmetrics',
            name='trainingEvent',
        ),
        migrations.DeleteModel(
            name='TrainingEvent',
        ),
    ]
