# Generated by Django 3.0.11 on 2021-03-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0152_auto_20210303_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='doi',
            name='authors_list',
            field=models.TextField(blank=True, null=True, verbose_name='Authors list'),
        ),
        migrations.AddField(
            model_name='doi',
            name='biblio_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='doi',
            name='journal_name',
            field=models.TextField(blank=True, null=True, verbose_name='Journal name'),
        ),
        migrations.AddField(
            model_name='doi',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
    ]
