# Generated by Django 3.0.11 on 2021-03-08 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0144_merge_20210119_1548'),
        ('ifbcat_api', '0153_auto_20210303_1551'),
    ]

    operations = [
    ]
