# Generated by Django 3.0.11 on 2021-03-17 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0154_merge_20210308_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computingfacility',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='eventsponsor',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='service',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='servicesubmission',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='trainingeventmetrics',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='trainingmaterial',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='servicesubmission',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='The year when the service was submitted for consideration of inclusion in the French SDP.', null=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
