# Generated by Django 3.0.11 on 2021-03-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0155_auto_20210317_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accessibilityNote',
            field=models.TextField(help_text='Comment about the audience a private event is open to and tailored for.'),
        ),
        migrations.AlterField(
            model_name='trainingevent',
            name='accessibilityNote',
            field=models.TextField(help_text='Comment about the audience a private event is open to and tailored for.'),
        ),
    ]
