# Generated by Django 3.0 on 2020-08-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0156_auto_20210318_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingEventMetrics',
        ),
    ]
