# Generated by Django 3.0.14 on 2021-05-11 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0157_delete_TrainingEventMetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name / title of the event.', max_length=255)),
                ('shortName', models.CharField(blank=True, help_text='Short name (or acronym) of the event.', max_length=255)),
                ('description', models.TextField(help_text='Description of the event.')),
                ('onlineOnly', models.BooleanField(blank=True, help_text='Whether the event is hosted online only.', null=True)),
                ('accessibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], help_text='Whether the event is public or private.', max_length=255)),
                ('accessibilityNote', models.TextField(help_text='Comment about the audience a private event is open to and tailored for.')),
                ('maxParticipants', models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of participants to the event.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('contactName', models.CharField(help_text='Name of person to contact about the event.', max_length=255)),
                ('contactEmail', models.EmailField(help_text='Email of person to contact about the event.', max_length=254)),
                ('logo_url', models.URLField(blank=True, help_text='URL of logo of event.', max_length=512, null=True)),
                ('difficultyLevel', models.CharField(blank=True, choices=[('Novice', 'Novice'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], help_text='The required experience and skills of the expected audience of the training event.', max_length=255)),
                ('learningOutcomes', models.TextField(blank=True, help_text='Expected learning outcomes from the training event.')),
                ('hoursPresentations', models.PositiveSmallIntegerField(blank=True, help_text='Total time (hours) of presented training material.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('hoursHandsOn', models.PositiveSmallIntegerField(blank=True, help_text='Total time (hours) of hands-on / practical work.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('hoursTotal', models.PositiveSmallIntegerField(blank=True, help_text='Total time investment (hours) of the training event, including recommended prework.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('personalised', models.BooleanField(blank=True, help_text='Whether the training is tailored to the individual in some way (BYOD, personal tutoring etc.)', null=True)),
                ('audienceRoles', models.ManyToManyField(blank=True, help_text='The professional roles of the expected audience of the training event.', to='ifbcat_api.AudienceRole')),
                ('audienceTypes', models.ManyToManyField(blank=True, help_text='The education or professional level of the expected audience of the training event.', to='ifbcat_api.AudienceType')),
                ('communities', models.ManyToManyField(blank=True, help_text='Community for which it is relevant.', to='ifbcat_api.Community')),
                ('computingFacilities', models.ManyToManyField(blank=True, help_text='Computing facilities that the training event uses.', to='ifbcat_api.ComputingFacility')),
                ('contactId', models.ForeignKey(help_text='IFB ID of person to contact about the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('costs', models.ManyToManyField(blank=True, help_text="Monetary cost to attend the event, e.g. 'Free to academics'.", to='ifbcat_api.EventCost')),
                ('elixirPlatforms', models.ManyToManyField(blank=True, help_text='ELIXIR Platform to which it is relevant.', to='ifbcat_api.ElixirPlatform')),
                ('keywords', models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the event.', to='ifbcat_api.Keyword')),
                ('organisedByOrganisations', models.ManyToManyField(blank=True, help_text='An organisation that is organizing it.', to='ifbcat_api.Organisation')),
                ('organisedByTeams', models.ManyToManyField(blank=True, help_text='A Team that is organizing it.', to='ifbcat_api.Team')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text="A skill which the audience should (ideally) possess to get the most out of the event, e.g. 'Python'.", to='ifbcat_api.EventPrerequisite')),
                ('prerequisites_trainings', models.ManyToManyField(blank=True, help_text='Trainings (ideally) already followed by the audience, or at least possess the expected outcomes.', to='ifbcat_api.Training')),
                ('sponsoredBy', models.ManyToManyField(blank=True, help_text='An institutional entity that is sponsoring it.', to='ifbcat_api.EventSponsor')),
                ('topics', models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the scope of the event.', to='ifbcat_api.Topic')),
                ('trainingMaterials', models.ManyToManyField(blank=True, help_text='Training material that the training event uses.', to='ifbcat_api.TrainingMaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingCourseMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField(help_text='The start date of the training event.')),
                ('dateEnd', models.DateField(help_text='The end date of the training event.')),
                ('numParticipants', models.PositiveSmallIntegerField(blank=True, help_text='Number of participants at the training event.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Training event metrics',
            },
        ),
        migrations.RemoveField(
            model_name='service',
            name='trainingEvents',
        ),
        migrations.AddField(
            model_name='event',
            name='computingFacilities',
            field=models.ManyToManyField(blank=True, help_text='Computing facilities that are used in the event.', to='ifbcat_api.ComputingFacility'),
        ),
        migrations.AddField(
            model_name='event',
            name='trainers',
            field=models.ManyToManyField(blank=True, help_text='Details of people who are providing training at the event.', to='ifbcat_api.Trainer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='communities',
            field=models.ManyToManyField(blank=True, help_text='Community for which it is relevant.', to='ifbcat_api.Community'),
        ),
        migrations.AlterField(
            model_name='event',
            name='elixirPlatforms',
            field=models.ManyToManyField(blank=True, help_text='ELIXIR Platform to which it is relevant.', to='ifbcat_api.ElixirPlatform'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisedByOrganisations',
            field=models.ManyToManyField(blank=True, help_text='An organisation that is organizing it.', to='ifbcat_api.Organisation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisedByTeams',
            field=models.ManyToManyField(blank=True, help_text='A Team that is organizing it.', to='ifbcat_api.Team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sponsoredBy',
            field=models.ManyToManyField(blank=True, help_text='An institutional entity that is sponsoring it.', to='ifbcat_api.EventSponsor'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainerId',
            field=models.ForeignKey(help_text='IFB ID of person who is providing training at the training event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TrainingEvent',
        ),
        migrations.AddField(
            model_name='trainingCourseMetrics',
            name='event',
            field=models.ForeignKey(help_text='Training event to which the metrics are associated.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ifbcat_api.Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='training',
            field=models.ForeignKey(blank=True, help_text="The training proposed, must be null if type is 'Training course', null otherwise.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbcat_api.Training'),
        ),
        migrations.AddField(
            model_name='service',
            name='trainings',
            field=models.ManyToManyField(blank=True, help_text='Training provided by the service.', related_name='services', to='ifbcat_api.Training'),
        ),
    ]
