# Generated by Django 3.0.14 on 2021-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0159_auto_20210511_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcoursemetrics',
            options={'verbose_name_plural': 'Training course metrics'},
        ),
        migrations.AddField(
            model_name='event',
            name='tess_publishing',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Auto')], default=2, help_text='Publish it in tess? Auto use training status, or Yes otherwise'),
        ),
        migrations.AddField(
            model_name='training',
            name='tess_publishing',
            field=models.BooleanField(default=True, help_text='Publish it in tess? Does associated events should also be published (unless explicitly indicated)?'),
        ),
    ]
