# Generated by Django 3.2.4 on 2021-09-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0160_auto_20210517_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdate',
            options={'ordering': ['dateStart']},
        ),
        migrations.AddField(
            model_name='event',
            name='registration_closing',
            field=models.DateField(blank=True, help_text='When does the registration for the event closes.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opening',
            field=models.DateField(blank=True, help_text='When does the registration for the event opens.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tess_publishing',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'Auto')], default=2, help_text='Publish it in tess? Auto use training status for training sessions, or Yes otherwise for'),
        ),
        migrations.AlterField(
            model_name='event',
            name='training',
            field=models.ForeignKey(blank=True, help_text="The training proposed, must be null if type is 'Training session', null otherwise.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbcat_api.training'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Workshop', 'Workshop'), ('Training course', 'Training session'), ('Meeting', 'Meeting'), ('Conference', 'Conference')], help_text="The type of event e.g. 'Training session'.", max_length=255),
        ),
    ]
