# Generated by Django 3.2.5 on 2021-10-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0161_auto_20210913_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text='Tool(s) developped by the team.', related_name='teams', to='ifbcat_api.Tool'),
        ),
    ]
