# Generated by Django 3.2.5 on 2021-11-25 15:49

from django.db import migrations, models
from django.db.models import Min, Max
import ifbcat_api.validators


def migrate_start_end_time(apps, schema_editor):
    Event = apps.get_model("ifbcat_api", "Event")
    result = Event.objects.annotate(t_start=Min('dates__timeStart'), t_end=Max('dates__timeEnd'))
    for e in result:
        e.time_start = e.t_start
        e.time_end = e.t_end
        e.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcat_api', '0164_auto_20211124_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_end',
            field=models.TimeField(blank=True, help_text='The end time of the event.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time_start',
            field=models.TimeField(blank=True, help_text='The start time of the event.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(
                help_text='Email address of a person (IFB catalogue user).',
                max_length=255,
                unique=True,
                validators=[ifbcat_api.validators.validate_email],
            ),
        ),
        migrations.RemoveField(
            model_name='event',
            name='dates',
        ),
        migrations.RunPython(code=migrate_start_end_time, reverse_code=migrations.RunPython.noop),
    ]
