# Generated by Django 3.2.5 on 2021-12-06 12:56

from django.db import migrations, models
import ifbcat_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0165_auto_20211130_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(help_text='Email address of a person (IFB catalogue user).', max_length=255, unique=True, validators=[ifbcat_api.validators.validate_email]),
        ),
    ]
