# Generated by Django 3.2.5 on 2021-11-29 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcat_api', '0165_auto_20211125_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDate',
        ),
    ]
