# Generated by Django 3.2.5 on 2021-12-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0166_alter_userprofile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventDate',
        ),
    ]
