# Generated by Django 3.2.5 on 2021-12-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0167_delete_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trainingMaterials',
            field=models.ManyToManyField(blank=True, help_text='Training material related to the training session.', to='ifbcat_api.TrainingMaterial'),
        ),
    ]
