# Generated by Django 3.2.5 on 2021-12-14 13:50

from django.db import migrations, models
import ifbcat_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0168_event_trainingmaterials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='uri',
            field=models.CharField(help_text='URI of EDAM Topic term describing scope or expertise. Go to https://edamontology.github.io/edam-browser/#topic_0003 to find new topics.', max_length=255, unique=True, validators=[ifbcat_api.validators.validate_edam_topic]),
        ),
    ]
