# Generated by Django 3.2.5 on 2022-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0169_alter_topic_uri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='onlineOnly',
        ),
        migrations.RemoveField(
            model_name='training',
            name='onlineOnly',
        ),
        migrations.AddField(
            model_name='event',
            name='courseMode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Hybrid', help_text='Select the mode for this event', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(blank=True, help_text="Mention whether it's a draft.", null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='courseMode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Hybrid', help_text='Select the mode for this event', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='is_draft',
            field=models.BooleanField(blank=True, help_text="Mention whether it's a draft.", null=True),
        ),
    ]
