# Generated by Django 3.2.5 on 2022-01-11 22:19

from django.db import migrations, models
from django.db.models import Case, When, Value, CharField, BooleanField


def migrate_onlineonly_to_coursemode(apps, schema_editor):
    apps.get_model("ifbcat_api", "Event").objects.filter(onlineOnly__isnull=False).update(
        courseMode=Case(
            When(onlineOnly=True, then=Value("Online")),
            default=Value("Onsite"),
        )
    )


def migrate_coursemode_to_onlineonly(apps, schema_editor):
    apps.get_model("ifbcat_api", "Event").objects.filter(courseMode__isnull=False).update(
        onlineOnly=Case(
            When(courseMode="Online", then=Value(True)),
            default=Value(False),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcat_api', '0169_alter_topic_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='courseMode',
            field=models.CharField(
                choices=[('Online', 'Online'), ('Onsite', 'Onsite'), ('Blended', 'Blended')],
                default=None,
                help_text='Select the mode for this event',
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=False, help_text="Mention whether it's a draft."),
        ),
        migrations.AddField(
            model_name='training',
            name='is_draft',
            field=models.BooleanField(default=False, help_text="Mention whether it's a draft."),
        ),
        migrations.RunPython(
            code=migrate_onlineonly_to_coursemode,
            reverse_code=migrate_coursemode_to_onlineonly,
        ),
        migrations.RemoveField(
            model_name='event',
            name='onlineOnly',
        ),
        migrations.RemoveField(
            model_name='training',
            name='onlineOnly',
        ),
    ]
