# Generated by Django 3.2.5 on 2022-01-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0170_auto_20220104_2356'),
        ('ifbcat_api', '0171_auto_20220124_1118'),
    ]

    operations = [
    ]
