# Generated by Django 3.2.5 on 2022-01-25 05:13

import django.db.models.deletion
from django.db import migrations, models
from django.db import migrations, models


def migrate_tool_license_into_licence(apps, schema_editor):
    Tool = apps.get_model("ifbcat_api", "Tool")
    Licence = apps.get_model("ifbcat_api", "Licence")
    for tool in Tool.objects.filter(tool_license__isnull=False):
        licence, created = Licence.objects.get_or_create(name=tool.tool_license)
        tool.tool_licence = licence
        tool.save()


def migrate_back(apps, schema_editor):
    Tool = apps.get_model("ifbcat_api", "Tool")
    Licence = apps.get_model("ifbcat_api", "Licence")
    for tool in Tool.objects.filter(tool_licence__isnull=False):
        tool.tool_license = tool.tool_licence.name
        tool.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcat_api', '0172_auto_20220104_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_licence',
            field=models.ForeignKey(blank=True, help_text='Licence of the tool.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='ifbcat_api.licence'),
        ),
        migrations.RunPython(code=migrate_tool_license_into_licence, reverse_code=migrate_back),
        migrations.RemoveField(
            model_name='tool',
            name='tool_license',
        ),
    ]
