# Generated by Django 3.2.5 on 2022-01-25 05:13

from django.db import migrations, models
import django.db.models.deletion


def migrate_tool_license(apps, schema_editor):
    Tool = apps.get_model("ifbcat_api", "Tool")
    Licence = apps.get_model("ifbcat_api", "Licence")
    for tool in Tool.objects.all():
        licence, created = Licence.objects.get_or_create(name=tool.tool_license)
        tool.link_tool_license = licence
        tool.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcat_api', '0172_auto_20220104_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='link_tool_license',
            field=models.ForeignKey(blank=True, help_text='Licence of the tool.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='ifbcat_api.licence'),
        ),
        migrations.RunPython(code=migrate_tool_license, reverse_code=migrations.RunPython.noop),
    ]
