# Generated by Django 3.2.5 on 2022-01-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0172_trainingmaterial_maintainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='training',
            field=models.ForeignKey(blank=True, help_text="The training proposed, must be provided if event type is 'Training session'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ifbcat_api.training'),
        ),
    ]
