# Generated by Django 3.2.5 on 2022-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0175_tool_link_tool_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='expertise',
            field=models.ManyToManyField(blank=True, help_text='Required for IFB platform and associated team. Please enter here one or several keywords describing the general and specific expertises of the team. Please note that individual expertises will also be documented in the "members" tab.', related_name='teamsExpertise', to='ifbcat_api.Topic'),
        ),
    ]
