# Generated by Django 3.2.5 on 2022-02-18 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0177_auto_20220218_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.AddField(
            model_name='team',
            name='leaders',
            field=models.ManyToManyField(blank=True, help_text='Leader(s) of the team.', related_name='teamsLeaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
