# Generated by Django 3.2.12 on 2022-02-28 13:41

from django.db import migrations, models
from django.db.models import Case, When, Value


def migrate_accessibility_to_openTo_event(apps, schema_editor):
    Event = apps.get_model("ifbcat_api", "Event")
    result = Event.objects.all()
    for e in result:
        if e.accessibility == "Private":
            e.openTo = "Internal personnel"
        elif e.accessibility == "Public":
            e.openTo = "Everyone"
        else:
            e.openTo = "Others"
        e.save()


def migrate_back_event(apps, schema_editor):
    Event = apps.get_model("ifbcat_api", "Event")
    result = Event.objects.all()
    for e in result:
        if e.openTo == "Internal personnel":
            e.accessibility = "Private"
        elif e.openTo == "Everyone":
            e.accessibility = "Public"
        else:
            e.accessibility = ""
        e.save()


def migrate_accessibility_to_openTo_training(apps, schema_editor):
    Training = apps.get_model("ifbcat_api", "Training")
    result = Training.objects.all()
    for t in result:
        if t.accessibility == "Private":
            t.openTo = "Internal personnel"
        elif t.accessibility == "Public":
            t.openTo = "Everyone"
        else:
            t.openTo = "Others"
        t.save()


def migrate_back_training(apps, schema_editor):
    Training = apps.get_model("ifbcat_api", "Training")
    result = Training.objects.all()
    for t in result:
        if t.openTo == "Internal personnel":
            t.accessibility = "Private"
        elif t.openTo == "Everyone":
            t.accessibility = "Public"
        else:
            t.accessibility = ""
        t.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcat_api', '0179_alter_community_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='accessibilityNote',
            new_name='accessConditions',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='accessibilityNote',
            new_name='accessConditions',
        ),
        migrations.AlterField(
            model_name='event',
            name='accessConditions',
            field=models.TextField(blank=True,
                                   help_text='Comment about the audience an event is open to and tailored for.',
                                   null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='accessConditions',
            field=models.TextField(blank=True,
                                   help_text='Comment about the audience an event is open to and tailored for.',
                                   null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='openTo',
            field=models.CharField(
                choices=[('Everyone', 'Everyone'), ('Internal personnel', 'Internal personnel'), ('Others', 'Others')],
                default='', help_text='Whether the event is for everyone, internal personnel or others.',
                max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='openTo',
            field=models.CharField(
                choices=[('Everyone', 'Everyone'), ('Internal personnel', 'Internal personnel'), ('Others', 'Others')],
                default='', help_text='Whether the event is for everyone, internal personnel or others.',
                max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(code=migrate_accessibility_to_openTo_event, reverse_code=migrate_back_event),
        migrations.RunPython(code=migrate_accessibility_to_openTo_training, reverse_code=migrate_back_training),
    ]