# Generated by Django 3.2.12 on 2022-02-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0179_alter_community_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='accessibilityNote',
            new_name='access_conditions',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='accessibility',
            new_name='open_to',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='accessibilityNote',
            new_name='access_conditions',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='accessibility',
            new_name='open_to',
        ),
    ]
