# Generated by Django 3.2.12 on 2022-03-07 09:51

from django.conf import settings
from django.db import migrations, models
from django.db.models import Exists


def migrate(apps, schema_editor):
    for klass in [apps.get_model("ifbcat_api", "Event"), apps.get_model("ifbcat_api", "Training")]:
        for o in klass.objects.filter(contactId__isnull=False):
            o.maintainers.add(o.contactId)


def migrate_back(apps, schema_editor):
    for klass in [apps.get_model("ifbcat_api", "Event"), apps.get_model("ifbcat_api", "Training")]:
        for o in klass.objects.exclude(maintainers=None):
            o.contactId = o.maintainers.first()
            o.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0180_auto_20220228_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maintainers',
            field=models.ManyToManyField(blank=True, help_text='Maintainer(s) can edit this object.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='maintainers',
            field=models.ManyToManyField(blank=True, help_text='Maintainer(s) can edit this object.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(code=migrate, reverse_code=migrate_back),
        migrations.RemoveField(
            model_name='event',
            name='contactId',
        ),
        migrations.RemoveField(
            model_name='training',
            name='contactId',
        ),
    ]
