# Generated by Django 3.2.12 on 2022-03-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0182_rename_trainers_event_trainers_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='source_repository',
            field=models.URLField(blank=True, help_text='URL to sources (GitLab, GitHub, ...)', max_length=512, null=True),
        ),
    ]
