# Generated by Django 3.2.12 on 2022-04-08 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0183_tool_source_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='maintainers',
            field=models.ManyToManyField(blank=True, help_text='A maintainer of a team in the IFB catalogue can edit its metadata.', related_name='teamsMaintainers', to=settings.AUTH_USER_MODEL),
        ),
    ]
