# Generated by Django 3.2.12 on 2022-06-01 11:30

from django.db import migrations, models
from django.db.models import Case, When, Value


def migrate(apps, schema_editor):
    apps.get_model("ifbcat_api", "Team").objects.update(
        ifbMembership=Case(
            When(ifbMembership='IFB platform', then=Value('Member platform')),
            When(ifbMembership='IFB-associated team', then=Value('Associated Team')),
            default=Value('None'),
        )
    )


def migrate_back(apps, schema_editor):
    apps.get_model("ifbcat_api", "Team").objects.update(
        ifbMembership=Case(
            When(ifbMembership='Member platform', then=Value('IFB platform')),
            When(ifbMembership='Associated Team', then=Value('IFB-associated team')),
            When(ifbMembership='Contributing platform', then=Value('IFB platform')),
            default=Value('None'),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0184_alter_team_maintainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ifbMembership',
            field=models.CharField(
                choices=[
                    ('Member platform', 'Member platform'),
                    ('Contributing platform', 'Contributing platform'),
                    ('Associated Team', 'Associated Team'),
                    ('None', 'None'),
                ],
                default='None',
                help_text='Type of membership the bioinformatics team has to IFB.',
                max_length=255,
            ),
        ),
        migrations.RunPython(code=migrate, reverse_code=migrate_back),
    ]
