# Generated by Django 3.2.12 on 2022-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0185_alter_team_ifbmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='closing_date',
            field=models.DateField(blank=True, default=None, help_text='After this date the team is closed. Leave blank if the team is still open/active.', null=True),
        ),
    ]
