# Generated by Django 3.2.12 on 2023-11-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0190_alter_team_ifbmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesubmission',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='servicesubmission',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicesubmission',
            name='submitters',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceSubmission',
        ),
    ]
