# Generated by Django 3.2.25 on 2024-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0192_ifb_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ifbMembership',
            field=models.CharField(
                choices=[
                    ('Associated Team', 'Associated Team'),
                    ('Contributing platform', 'Contributing platform'),
                    ('Coordinating platform', 'Coordinating unit'),
                    ('Member platform', 'Member platform'),
                    ('None', 'None'),
                ],
                default='None',
                help_text='Type of membership the bioinformatics team has to IFB.',
                max_length=255,
            ),
        ),
    ]
