# Generated by Django 4.2.14 on 2024-08-05 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0193_alter_team_ifbmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maintainers',
            field=models.ManyToManyField(
                blank=True,
                help_text='Maintainer(s) can edit this object.',
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='training',
            name='maintainers',
            field=models.ManyToManyField(
                blank=True,
                help_text='Maintainer(s) can edit this object.',
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
