# Generated by Django 3.2.12 on 2022-06-01 11:30

from django.db import migrations, models


def migrate(apps, schema_editor):
    apps.get_model("ifbcat_api", "Team").objects.filter(ifbMembership='Coordinating platform').update(
        ifbMembership='Coordinating unit'
    )


def migrate_back(apps, schema_editor):
    apps.get_model("ifbcat_api", "Team").objects.filter(ifbMembership='Coordinating unit').update(
        ifbMembership='Coordinating platform'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0194_alter_event_maintainers_alter_training_maintainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ifbMembership',
            field=models.CharField(
                choices=[
                    ('Associated Team', 'Associated Team'),
                    ('Contributing platform', 'Contributing platform'),
                    ('Coordinating unit', 'Coordinating unit'),
                    ('Member platform', 'Member platform'),
                    ('None', 'None'),
                ],
                default='None',
                help_text='Type of membership the bioinformatics team has to IFB.',
                max_length=255,
            ),
        ),
        migrations.RunPython(code=migrate, reverse_code=migrate_back),
    ]
