# Generated by Django 4.2.24 on 2025-10-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0195_alter_team_ifbmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='affiliatedWith',
            field=models.ManyToManyField(
                blank=True,
                help_text='Organisation(s) to which the team is affiliated. i.e: "Laboratoire" or "unité" in french',
                related_name='teamsAffiliatedWith',
                to='ifbcat_api.organisation',
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='fundedBy',
            field=models.ManyToManyField(
                help_text='Organisation(s) that funds the team. i.e the "tutelle" in french',
                related_name='teamsFunders',
                to='ifbcat_api.organisation',
            ),
        ),
        migrations.AlterField(
            model_name='team',
            name='tools',
            field=models.ManyToManyField(
                blank=True,
                help_text='Tool(s) developped by the team. You just need to provide a BioTools id.',
                related_name='teams',
                to='ifbcat_api.tool',
            ),
        ),
    ]
