# Generated by Django 4.2.24 on 2025-10-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0195_alter_team_ifbmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(help_text='Description of the team.', max_length=800),
        ),
    ]
