# Generated by Django 4.2.24 on 2025-10-17 13:58

from django.db import migrations, models
import ifbcat_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcat_api', '0196_team_expertise_description_alter_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='expertise_description',
            field=models.TextField(blank=True, help_text="Short description of the team's expertise.", max_length=400),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(
                blank=True,
                help_text='URL of logo of the team.',
                max_length=512,
                null=True,
                validators=[ifbcat_api.validators.validate_https, ifbcat_api.validators.MaxFileSizeValidator(250)],
            ),
        ),
    ]
