# Generated by Django 2.2 on 2020-06-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0004_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsItem',
        ),
    ]
