# Generated by Django 2.2 on 2020-06-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0005_auto_20200628_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortName', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('homepage', models.URLField(blank=True, max_length=255, null=True)),
                ('venue', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('onlineOnly', models.BooleanField(blank=True, null=True)),
                ('accessibilityNote', models.CharField(blank=True, max_length=255)),
                ('maxParticipants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contactName', models.CharField(max_length=255)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('market', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='orcidid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
