# Generated by Django 3.0 on 2020-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0009_auto_20200701_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maxParticipants',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
