# Generated by Django 3.0 on 2020-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0012_auto_20200701_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='accessibilityNote',
            field=models.CharField(blank=True, help_text='Comment about the audience a private event is open to and tailored for.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, help_text='The nearest city to where the event will be held.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='contactEmail',
            field=models.EmailField(help_text='Email of person to contact about the event.', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='contactName',
            field=models.CharField(help_text='Name of person to contact about the event.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, help_text='The country where the event will be held.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Description of the event.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='homepage',
            field=models.URLField(blank=True, help_text='URL of event homepage.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='market',
            field=models.CharField(blank=True, help_text='Geographical area which is the focus of event marketing efforts.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='maxParticipants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of participants to the event.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Full name / title of the event.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='onlineOnly',
            field=models.BooleanField(blank=True, help_text='Whether the event is hosted online only.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='shortName',
            field=models.CharField(blank=True, help_text='Short name (or acronym) of the event.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('WO', 'Workshop'), ('TR', 'Training course'), ('ME', 'Meeting'), ('CO', 'Conference')], help_text="The type of event e.g. 'Training course'.", max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.TextField(blank=True, help_text='The address of the venue where the event will be held.'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='news_text',
            field=models.CharField(help_text='Some news provided by a user.', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Whether a user has staff status.'),
        ),
    ]
