# Generated by Django 3.0 on 2020-07-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0015_auto_20200702_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the event.', max_length=255)),
            ],
        ),
    ]
