# Generated by Django 3.0 on 2020-07-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0020_eventprerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='URI of EDAM Topic term describing the scope of the event.', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(related_name='events', to='ifbcatsandbox_api.EventTopic'),
        ),
    ]
