# Generated by Django 3.0 on 2020-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0023_auto_20200715_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Workshop', 'Workshop'), ('Training course', 'Training Course'), ('Meeting', 'Meeting'), ('Conference', 'Conference')], help_text="The type of event e.g. 'Training course'.", max_length=255),
        ),
    ]
