# Generated by Django 3.0 on 2020-07-16 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0026_auto_20200716_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maxParticipants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of participants to the event.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
