# Generated by Django 3.0 on 2020-07-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0028_auto_20200716_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.CharField(choices=[('Free', 'Free'), ('Free to academics', 'Free To Academics'), ('Priced', 'Priced'), ('Concessions available', 'Concessions Available')], help_text="Monetary cost to attend the event, e.g. 'Free to academics'.", max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.ManyToManyField(help_text="Monetary cost to attend the event, e.g. 'Free to academics'.", related_name='events', to='ifbcatsandbox_api.EventCost'),
        ),
    ]
