# Generated by Django 3.0 on 2020-07-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0031_auto_20200716_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcost',
            name='cost',
            field=models.CharField(choices=[('Free', 'Free'), ('Free to academics', 'Free To Academics'), ('Priced', 'Priced'), ('Concessions available', 'Concessions Available')], help_text="Monetary cost to attend the event, e.g. 'Free to academics'.", max_length=255, unique=True),
        ),
    ]
