# Generated by Django 3.0 on 2020-07-20 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0036_auto_20200720_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elixirplatform',
            name='coordinator',
            field=models.ForeignKey(help_text='Coordinator of the ELIXIR Platform activities in France.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elixirPlatformCoordinator', to=settings.AUTH_USER_MODEL),
        ),
    ]
