# Generated by Django 3.0 on 2020-07-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0051_auto_20200721_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='field',
            new_name='fields',
        ),
    ]
