# Generated by Django 3.0 on 2020-07-20 19:17

from django.db import migrations, models


def migration_code(apps, schema_editor):
    EventCost = apps.get_model("ifbcatsandbox_api", "EventCost")

    for name in [
        'Free', 'Free to academics', 'Priced', 'Concessions available',

    ]:
        EventCost.objects.get_or_create(
            cost=name,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcatsandbox_api', '0056_project_user_profile'),
    ]

    operations = [
        migrations.RunPython(migration_code, reverse_code=migrations.RunPython.noop),
    ]
