# Generated by Django 3.0 on 2020-07-20 19:17

from django.db import migrations, models


def migration_code(apps, schema_editor):
    OrganisationField = apps.get_model("ifbcatsandbox_api", "OrganisationField")

    for s in [
        'Computer science',
        'Biotechnology',
        'Environmental science',
        'Agricultural science',
        'Biomedical science',
        'Biology',
    ]:
        OrganisationField.objects.get_or_create(
            field=s,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('ifbcatsandbox_api', '0057_create_cost'),
    ]

    operations = [
        migrations.RunPython(migration_code, reverse_code=migrations.RunPython.noop),
    ]
