# Generated by Django 3.0 on 2020-08-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0063_computingfacility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computingfacility',
            options={'verbose_name_plural': 'Computing facilities'},
        ),
    ]
