# Generated by Django 3.0 on 2020-08-13 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0066_auto_20200813_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='trainerId',
            field=models.ForeignKey(help_text='IFB ID of person who is providing training at the training event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainerId', to=settings.AUTH_USER_MODEL),
        ),
    ]
