# Generated by Django 3.0 on 2020-08-19 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0071_auto_20200818_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingeventmetrics',
            options={'verbose_name_plural': 'Training event metrics'},
        ),
        migrations.AddField(
            model_name='team',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='expertise',
            field=models.ManyToManyField(help_text='URIs of EDAM Topic terms describing the expertise of the team.', related_name='teams', to='ifbcatsandbox_api.EventTopic'),
        ),
    ]
