# Generated by Django 3.0 on 2020-08-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0076_event_sponsoredby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computingfacility',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Computing facilities'},
        ),
        migrations.AddField(
            model_name='project',
            name='uses',
            field=models.ManyToManyField(blank=True, help_text='A computing facility which the project uses.', related_name='projects', to='ifbcatsandbox_api.ComputingFacility'),
        ),
    ]
