# Generated by Django 3.0 on 2020-08-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0081_auto_20200820_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventKeyword',
        ),
    ]
