# Generated by Django 3.0 on 2020-08-25 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0082_delete_eventkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service.', max_length=255)),
                ('description', models.TextField(help_text='Short desccripion of the service.')),
                ('dateEstablished', models.DateField(help_text='Date when the service was first established and started operating.')),
                ('governanceSab', models.URLField(blank=True, help_text='Link to the description of the SAB covering the service.', max_length=255, null=True)),
                ('bioinformaticsTeams', models.ManyToManyField(help_text='The bioinformatics team(s) that provides this service.', related_name='services', to='ifbcatsandbox_api.BioinformaticsTeam')),
                ('computingFacilities', models.ManyToManyField(blank=True, help_text='Computing facilities provided by the service.', related_name='servicesComputingFacilities', to='ifbcatsandbox_api.BioinformaticsTeam')),
                ('publications', models.ManyToManyField(blank=True, help_text='Publication(s) that describe the service as a whole.', related_name='services', to='ifbcatsandbox_api.Doi')),
                ('trainingEvents', models.ManyToManyField(blank=True, help_text='Training event(s) provided by the service.', related_name='services', to='ifbcatsandbox_api.TrainingEvent')),
                ('trainingMaterials', models.ManyToManyField(blank=True, help_text='Training material(s) provided by the service.', related_name='servicesTrainingMaterials', to='ifbcatsandbox_api.TrainingMaterial')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
