# Generated by Django 3.0 on 2020-08-26 15:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0085_trainingmaterial_providedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='The year when the service was submitted for consideration of incluson in the French SDP.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('motivation', models.TextField(help_text='Motivation for making the submission.')),
                ('scope', models.TextField(help_text='Scope of the service including domain covered, relevance, originality, links with EU infrastructures, community leadership roles, and positioning regarding similar resources (especially of ELIXIR nodes and platforms).')),
                ('caseForSupport', models.TextField(help_text='The motivation for the service and why it should be supported by IFB and/or included in the SDP.')),
                ('qaqc', models.TextField(help_text='Short description of quality assurance and control processes in place aimed to ensure a high-quality service.')),
                ('usage', models.TextField(help_text='Description of the extent and ways the service is used, including quantitatve usage metrics or indicators.')),
                ('sustainability', models.TextField(help_text='Service funding and sustainability plan, including past and future funding commitments, and number of FTE engaged during the last four years and next year.')),
                ('authors', models.ManyToManyField(help_text='The person(s) who submitted the service proposal to the ELIXIR FR SDP process.', null=True, related_name='ServiceSubmissionAuthor', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(help_text='The service associated with this submission to the ELIXIR FR SDP process.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ServiceSubmission', to='ifbcatsandbox_api.Service')),
                ('submitters', models.ManyToManyField(help_text='The person(s) who submitted the service proposal to the ELIXIR FR SDP process.', null=True, related_name='ServiceSubmissionSubmitter', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
