# Generated by Django 3.0 on 2020-08-26 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0087_auto_20200826_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Full name / title of the event.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 \\-_~]+$', 'Should only contains char such as ^[a-zA-Z0-9\\-_~]')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Name of the project.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 \\-_~]+$', 'Should only contains char such as ^[a-zA-Z0-9\\-_~]')]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(help_text='Name of the resource.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 \\-_~]+$', 'Should only contains char such as ^[a-zA-Z0-9\\-_~]')]),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Short description of the service.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Name of the service.', max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 \\-_~]+$', 'Should only contains char such as ^[a-zA-Z0-9\\-_~]')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Name of the team.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 \\-_~]+$', 'Should only contains char such as ^[a-zA-Z0-9\\-_~]')]),
        ),
    ]
