# Generated by Django 3.0 on 2020-08-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0089_auto_20200827_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganisationField',
        ),
    ]
