# Generated by Django 3.0 on 2020-08-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0092_auto_20200827_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTopic',
        ),
    ]
