# Generated by Django 3.0.7 on 2020-09-02 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0096_auto_20200902_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsponsor',
            name='name',
            field=models.CharField(help_text='Name of institutional entity that is sponsoring the event.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Name of the service.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 \\-_~]+$', 'Should only contains char such as ^[a-zA-Z0-9\\-_~]')]),
        ),
    ]
