# Generated by Django 3.0 on 2020-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0097_auto_20200902_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computingfacility',
            name='accessibility',
            field=models.CharField(choices=[('Internal', 'Internal'), ('National', 'National'), ('International', 'International')], help_text='Accessibillity of the computing facility to end-users.', max_length=255),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='requestAccount',
            field=models.URLField(blank=True, help_text='URL of web page where one can request access to the computing facility.', max_length=255),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='serverDescription',
            field=models.CharField(blank=True, help_text='Description of number and type of servers.', max_length=255),
        ),
        migrations.AlterField(
            model_name='computingfacility',
            name='termsOfUse',
            field=models.URLField(blank=True, help_text='URL where terms of use of the computing facility can be found.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='homepage',
            field=models.URLField(default='https://test.com', help_text='URL of event homepage.', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='homepage',
            field=models.URLField(default='https://test.com', help_text='Homepage of the team.', max_length=255),
        ),
    ]
