# Generated by Django 3.0 on 2020-09-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0099_auto_20200902_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='costs',
            field=models.ManyToManyField(blank=True, help_text="Monetary cost to attend the event, e.g. 'Free to academics'.", related_name='events', to='ifbcatsandbox_api.EventCost'),
        ),
        migrations.AlterField(
            model_name='event',
            name='keywords',
            field=models.ManyToManyField(blank=True, help_text='A keyword (beyond EDAM ontology scope) describing the event.', related_name='events', to='ifbcatsandbox_api.Keyword'),
        ),
        migrations.AlterField(
            model_name='event',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text="A skill which the audience should (ideally) possess to get the most out of the event, e.g. 'Python'.", related_name='events', to='ifbcatsandbox_api.EventPrerequisite'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the scope of the event.', related_name='events', to='ifbcatsandbox_api.Topic'),
        ),
        migrations.AlterField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the expertise of the project.', related_name='projects', to='ifbcatsandbox_api.Topic'),
        ),
        migrations.AlterField(
            model_name='team',
            name='expertise',
            field=models.ManyToManyField(blank=True, help_text='URIs of EDAM Topic terms describing the expertise of the team.', related_name='teams', to='ifbcatsandbox_api.Topic'),
        ),
        migrations.AlterField(
            model_name='trainingeventmetrics',
            name='trainingEvent',
            field=models.ForeignKey(default='3', help_text='Training event to which the metrics are associated.', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='ifbcatsandbox_api.TrainingEvent'),
        ),
    ]
