# Generated by Django 3.0 on 2020-09-03 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0103_auto_20200903_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubmission',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='The year when the service was submitted for consideration of incluson in the French SDP.', null=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
