# Generated by Django 3.0.7 on 2020-09-04 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ifbcatsandbox_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ifbcatsandbox_api', '0110_auto_20200904_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='orgid',
            field=models.CharField(blank=True, help_text='Organisation ID (GRID or ROR ID) of the organisation.', max_length=255, null=True, unique=True, validators=[ifbcatsandbox_api.validators.validate_grid_or_ror_id]),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
