name: black

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: run black
      run: |
        black . --check --diff
