name: Checking migrations

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check if no migrations is missing
      run: |
        cp resources/default.ini local.ini     
        docker-compose build
        docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d
        sleep 10
        docker-compose exec web python manage.py makemigrations --check
