name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository:  IFB-ElixirFr/ifbcat-importdata
        token: ${{ secrets.ACCESS_TOKEN }}
        path: 'import_data'
    - name: Run the DB locally
      run: |
        cp resources/default.ini local.ini
        docker-compose build
        docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d
        docker-compose exec -T -e DJANGO_SUPERUSER_PASSWORD web python manage.py createsuperuser --no-input --email super.user@test.com --firstname super --lastname user
        docker-compose exec -T web python manage.py migrate
        docker-compose exec -T web python manage.py test
      env:
        DJANGO_SUPERUSER_PASSWORD: test_password
