name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository:  IFB-ElixirFr/ifbcat-importdata
        token: ${{ secrets.ACCESS_TOKEN }}
        #ssh-key: ${{ secrets.DEPLOY_KEY }}
        path: 'import_data'
    - run: ls; pwd
