name: tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository:  IFB-ElixirFr/ifbcat-importdata
        token: ${{ secrets.ACCESS_TOKEN }}
        path: 'import_data'
    - name: Run the DB locally
      run: |
        cp resources/default.ini local.ini
        docker-compose build
        docker-compose -f docker-compose.yaml -f docker-compose.dev.yaml up -d
        docker-compose exec -T -e DJANGO_SUPERUSER_PASSWORD -e DJANGO_SUPERUSER_USERNAME -e DJANGO_SUPERUSER_EMAIL web python manage.py createsuperuser --no-input
        docker-compose exec web python manage.py migrate
        docker-compose exec web python manage.py test
      env:
        DJANGO_SUPERUSER_PASSWORD: test_password
        DJANGO_SUPERUSER_USERNAME: test_username
        DJANGO_SUPERUSER_EMAIL: test@email.com
